import type { PackageRecord } from "@/features/packages-example/types";

export const PACKAGE_MOCK_RECORDS: readonly PackageRecord[] = [
  {
    id: "react",
    name: "react",
    description: "UI library used across every list page",
    version: "19.2.8",
    dependencyType: "dependency",
    updateStatus: "up-to-date",
  },
  {
    id: "react-dom",
    name: "react-dom",
    description: "React's renderer for the browser DOM",
    version: "19.2.8",
    dependencyType: "dependency",
    updateStatus: "up-to-date",
  },
  {
    id: "next",
    name: "next",
    description: "App Router framework powering routing and Route Handlers",
    version: "16.3.3",
    dependencyType: "dependency",
    updateStatus: "up-to-date",
  },
  {
    id: "next-themes",
    name: "next-themes",
    description: "Light, dark, and system theme switching",
    version: "0.4.6",
    dependencyType: "dependency",
    updateStatus: "minor-update",
  },
  {
    id: "base-ui-react",
    name: "@base-ui/react",
    description: "Accessible primitives behind Popover, Sheet, and ToggleGroup",
    version: "1.7.0",
    dependencyType: "dependency",
    updateStatus: "outdated",
  },
  {
    id: "class-variance-authority",
    name: "class-variance-authority",
    description: "Variant styling for shadcn/ui components",
    version: "0.7.1",
    dependencyType: "dependency",
    updateStatus: "up-to-date",
  },
  {
    id: "clsx",
    name: "clsx",
    description: "Conditional className composition used by cn()",
    version: "2.1.1",
    dependencyType: "dependency",
    updateStatus: "outdated",
  },
  {
    id: "shadcn",
    name: "shadcn",
    description: "CLI for adding and updating owned shadcn/ui primitives",
    version: "4.19.0",
    dependencyType: "dependency",
    updateStatus: "up-to-date",
  },
  {
    id: "tailwind-merge",
    name: "tailwind-merge",
    description: "Resolves conflicting Tailwind utility classes in cn()",
    version: "3.6.0",
    dependencyType: "dependency",
    updateStatus: "up-to-date",
  },
  {
    id: "tw-animate-css",
    name: "tw-animate-css",
    description: "Utility animation classes for motion-safe transitions",
    version: "1.4.0",
    dependencyType: "dependency",
    updateStatus: "minor-update",
  },
  {
    id: "biomejs-biome",
    name: "@biomejs/biome",
    description: "Linting and formatting across the codebase",
    version: "2.4.2",
    dependencyType: "devDependency",
    updateStatus: "up-to-date",
  },
  {
    id: "tailwindcss-postcss",
    name: "@tailwindcss/postcss",
    description: "PostCSS plugin that compiles Tailwind CSS 4",
    version: "4.1.12",
    dependencyType: "devDependency",
    updateStatus: "minor-update",
  },
  {
    id: "types-node",
    name: "@types/node",
    description: "Type definitions for the Node.js runtime",
    version: "20.14.10",
    dependencyType: "devDependency",
    updateStatus: "outdated",
  },
  {
    id: "types-react",
    name: "@types/react",
    description: "Type definitions for React",
    version: "19.1.2",
    dependencyType: "devDependency",
    updateStatus: "up-to-date",
  },
  {
    id: "types-react-dom",
    name: "@types/react-dom",
    description: "Type definitions for react-dom",
    version: "19.1.2",
    dependencyType: "devDependency",
    updateStatus: "up-to-date",
  },
  {
    id: "babel-plugin-react-compiler",
    name: "babel-plugin-react-compiler",
    description: "Enables the React Compiler's automatic memoization",
    version: "1.0.0",
    dependencyType: "devDependency",
    updateStatus: "minor-update",
  },
  {
    id: "tailwindcss",
    name: "tailwindcss",
    description: "Utility-first styling with CSS-variable theme tokens",
    version: "4.1.12",
    dependencyType: "devDependency",
    updateStatus: "outdated",
  },
  {
    id: "typescript",
    name: "typescript",
    description: "Strict type-checking across the codebase",
    version: "5.6.3",
    dependencyType: "devDependency",
    updateStatus: "up-to-date",
  },
];
