import { ASSIGNEES } from "@/features/issues-example/config";
import type { IssueRecord } from "@/features/issues-example/types";

const [nora, idris, priya, owen] = ASSIGNEES;

export const ISSUE_MOCK_RECORDS: readonly IssueRecord[] = [
  {
    id: "issue-201",
    number: 201,
    title: "Pagination controls jump to page 1 after a filter change",
    status: "open",
    priority: "high",
    label: "bug",
    assignee: nora,
    createdAt: "2026-08-29",
    updatedAt: "2026-08-31",
  },
  {
    id: "issue-200",
    number: 200,
    title: "Add a keyboard shortcut to focus the search field",
    status: "in_progress",
    priority: "medium",
    label: "enhancement",
    assignee: idris,
    createdAt: "2026-08-27",
    updatedAt: "2026-08-30",
  },
  {
    id: "issue-199",
    number: 199,
    title: "Sort menu keeps the previous label after selecting a new option",
    status: "open",
    priority: "high",
    label: "bug",
    assignee: priya,
    createdAt: "2026-08-25",
    updatedAt: "2026-08-30",
  },
  {
    id: "issue-198",
    number: 198,
    title: "Bulk close should ask for confirmation before applying",
    status: "open",
    priority: "medium",
    label: "ux",
    assignee: nora,
    createdAt: "2026-08-24",
    updatedAt: "2026-08-29",
  },
  {
    id: "issue-197",
    number: 197,
    title: "Empty state copy reads the same across every example page",
    status: "closed",
    priority: "low",
    label: "content",
    assignee: null,
    createdAt: "2026-08-20",
    updatedAt: "2026-08-28",
  },
  {
    id: "issue-196",
    number: 196,
    title: "Assignee filter has no option for unassigned issues",
    status: "in_progress",
    priority: "medium",
    label: "enhancement",
    assignee: owen,
    createdAt: "2026-08-19",
    updatedAt: "2026-08-27",
  },
  {
    id: "issue-195",
    number: 195,
    title: "Selected count is off by one right after select-all",
    status: "closed",
    priority: "high",
    label: "bug",
    assignee: priya,
    createdAt: "2026-08-18",
    updatedAt: "2026-08-26",
  },
  {
    id: "issue-194",
    number: 194,
    title: "Row hover state is invisible in dark mode",
    status: "open",
    priority: "low",
    label: "bug",
    assignee: null,
    createdAt: "2026-08-17",
    updatedAt: "2026-08-25",
  },
  {
    id: "issue-193",
    number: 193,
    title: "Document the query-state flow for a new list page",
    status: "in_progress",
    priority: "low",
    label: "docs",
    assignee: idris,
    createdAt: "2026-08-15",
    updatedAt: "2026-08-24",
  },
  {
    id: "issue-192",
    number: 192,
    title: "Large result sets cause a noticeable scroll jank",
    status: "open",
    priority: "medium",
    label: "performance",
    assignee: owen,
    createdAt: "2026-08-14",
    updatedAt: "2026-08-23",
  },
  {
    id: "issue-191",
    number: 191,
    title: "Filter chips wrap awkwardly at the tablet breakpoint",
    status: "closed",
    priority: "low",
    label: "ux",
    assignee: nora,
    createdAt: "2026-08-13",
    updatedAt: "2026-08-22",
  },
  {
    id: "issue-190",
    number: 190,
    title: "Add optimistic feedback while a bulk action is pending",
    status: "in_progress",
    priority: "medium",
    label: "enhancement",
    assignee: priya,
    createdAt: "2026-08-12",
    updatedAt: "2026-08-21",
  },
  {
    id: "issue-189",
    number: 189,
    title: "Retry button on the error state does not clear the old message",
    status: "open",
    priority: "high",
    label: "bug",
    assignee: idris,
    createdAt: "2026-08-11",
    updatedAt: "2026-08-20",
  },
  {
    id: "issue-188",
    number: 188,
    title: "Explain the difference between search and filters in the docs",
    status: "closed",
    priority: "low",
    label: "docs",
    assignee: null,
    createdAt: "2026-08-10",
    updatedAt: "2026-08-19",
  },
  {
    id: "issue-187",
    number: 187,
    title: "Priority label is unreadable against the warning background",
    status: "open",
    priority: "medium",
    label: "bug",
    assignee: owen,
    createdAt: "2026-08-09",
    updatedAt: "2026-08-18",
  },
  {
    id: "issue-186",
    number: 186,
    title: "Selection banner should announce updates for screen readers",
    status: "in_progress",
    priority: "high",
    label: "ux",
    assignee: nora,
    createdAt: "2026-08-08",
    updatedAt: "2026-08-17",
  },
  {
    id: "issue-185",
    number: 185,
    title: "Long issue titles overflow the label column on narrow screens",
    status: "closed",
    priority: "low",
    label: "bug",
    assignee: priya,
    createdAt: "2026-08-07",
    updatedAt: "2026-08-16",
  },
  {
    id: "issue-184",
    number: 184,
    title: "Support clearing a single filter without resetting the others",
    status: "open",
    priority: "medium",
    label: "enhancement",
    assignee: idris,
    createdAt: "2026-08-06",
    updatedAt: "2026-08-15",
  },
  {
    id: "issue-183",
    number: 183,
    title: "Table header checkbox does not reach indeterminate state",
    status: "closed",
    priority: "high",
    label: "bug",
    assignee: owen,
    createdAt: "2026-08-05",
    updatedAt: "2026-08-14",
  },
  {
    id: "issue-182",
    number: 182,
    title: "Add a compact card layout for narrower viewports",
    status: "in_progress",
    priority: "low",
    label: "enhancement",
    assignee: null,
    createdAt: "2026-08-04",
    updatedAt: "2026-08-13",
  },
  {
    id: "issue-181",
    number: 181,
    title: "Loading skeleton column widths drift from the loaded table",
    status: "open",
    priority: "low",
    label: "bug",
    assignee: nora,
    createdAt: "2026-08-03",
    updatedAt: "2026-08-12",
  },
  {
    id: "issue-180",
    number: 180,
    title: "Consider a performance budget for the results view",
    status: "closed",
    priority: "medium",
    label: "performance",
    assignee: priya,
    createdAt: "2026-08-02",
    updatedAt: "2026-08-11",
  },
  {
    id: "issue-179",
    number: 179,
    title: "Updated-time labels do not refresh without a page reload",
    status: "open",
    priority: "low",
    label: "bug",
    assignee: idris,
    createdAt: "2026-08-01",
    updatedAt: "2026-08-10",
  },
  {
    id: "issue-178",
    number: 178,
    title: "Rename the Label filter to something less ambiguous",
    status: "closed",
    priority: "low",
    label: "content",
    assignee: null,
    createdAt: "2026-07-30",
    updatedAt: "2026-08-09",
  },
  {
    id: "issue-177",
    number: 177,
    title: "Focus outline is clipped on the first row after scrolling",
    status: "open",
    priority: "high",
    label: "bug",
    assignee: owen,
    createdAt: "2026-07-29",
    updatedAt: "2026-08-08",
  },
  {
    id: "issue-176",
    number: 176,
    title: "Add a Templates link from the empty results state",
    status: "in_progress",
    priority: "low",
    label: "ux",
    assignee: nora,
    createdAt: "2026-07-28",
    updatedAt: "2026-08-07",
  },
];
