import { BRANCHES } from "@/features/deployments-example/config";
import type { DeploymentRecord } from "@/features/deployments-example/types";

const MINUTE_MS = 60 * 1000;

/** ISO datetime `minutes` before the moment this module was evaluated. */
function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * MINUTE_MS).toISOString();
}

const [
  main,
  bulkActions,
  sortMenu,
  viewSwitcher,
  deps,
  paginationEdge,
  filterPanelMobile,
  queryStateGuide,
] = BRANCHES;

export const DEPLOYMENT_MOCK_RECORDS: readonly DeploymentRecord[] = [
  {
    id: "deploy-226",
    branch: main,
    commitMessage: "Fix pagination edge case on last page",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(12),
  },
  {
    id: "deploy-225",
    branch: bulkActions,
    commitMessage: "Add bulk status change to issues list",
    environment: "preview",
    status: "building",
    deployedAt: minutesAgo(18),
  },
  {
    id: "deploy-224",
    branch: filterPanelMobile,
    commitMessage: "Collapse secondary filters behind More filters on mobile",
    environment: "preview",
    status: "ready",
    deployedAt: minutesAgo(47),
  },
  {
    id: "deploy-223",
    branch: main,
    commitMessage: "Update filter panel accessibility labels",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(60),
  },
  {
    id: "deploy-222",
    branch: sortMenu,
    commitMessage: "Sort menu now reflects active field",
    environment: "staging",
    status: "failed",
    deployedAt: minutesAgo(120),
  },
  {
    id: "deploy-221",
    branch: viewSwitcher,
    commitMessage: "Add grid view to components list",
    environment: "preview",
    status: "ready",
    deployedAt: minutesAgo(180),
  },
  {
    id: "deploy-220",
    branch: main,
    commitMessage: "Deploy mock data route handlers",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(240),
  },
  {
    id: "deploy-219",
    branch: deps,
    commitMessage: "Bump Tailwind CSS to v4.0",
    environment: "staging",
    status: "building",
    deployedAt: minutesAgo(360),
  },
  {
    id: "deploy-218",
    branch: paginationEdge,
    commitMessage: "Clamp requested page to the last valid page",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(540),
  },
  {
    id: "deploy-217",
    branch: queryStateGuide,
    commitMessage: "Document the query-state flow for a new list page",
    environment: "preview",
    status: "ready",
    deployedAt: minutesAgo(840),
  },
  {
    id: "deploy-216",
    branch: main,
    commitMessage: "Add SelectionToolbar to the shared list architecture",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(1200),
  },
  {
    id: "deploy-215",
    branch: sortMenu,
    commitMessage: "Fix sort menu keyboard focus trap",
    environment: "staging",
    status: "failed",
    deployedAt: minutesAgo(1440),
  },
  {
    id: "deploy-214",
    branch: bulkActions,
    commitMessage: "Disable selection controls while a bulk action is pending",
    environment: "preview",
    status: "ready",
    deployedAt: minutesAgo(1800),
  },
  {
    id: "deploy-213",
    branch: main,
    commitMessage: "Narrow the client boundary around the search field",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(2880),
  },
  {
    id: "deploy-212",
    branch: viewSwitcher,
    commitMessage: "Persist view mode in the URL instead of local state",
    environment: "preview",
    status: "building",
    deployedAt: minutesAgo(3720),
  },
  {
    id: "deploy-211",
    branch: filterPanelMobile,
    commitMessage: "Trap focus inside the mobile filter drawer",
    environment: "staging",
    status: "ready",
    deployedAt: minutesAgo(4320),
  },
  {
    id: "deploy-210",
    branch: main,
    commitMessage: "Reset pagination when a filter changes the result set",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(5760),
  },
  {
    id: "deploy-209",
    branch: deps,
    commitMessage: "Upgrade to Next.js 16 and React 19",
    environment: "preview",
    status: "failed",
    deployedAt: minutesAgo(7200),
  },
  {
    id: "deploy-208",
    branch: paginationEdge,
    commitMessage: "Show ellipses in pagination for large page counts",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(8640),
  },
  {
    id: "deploy-207",
    branch: main,
    commitMessage: "Introduce demoState for loading, empty and error previews",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(9840),
  },
  {
    id: "deploy-206",
    branch: queryStateGuide,
    commitMessage: "Rewrite the reusable list-page architecture overview",
    environment: "preview",
    status: "ready",
    deployedAt: minutesAgo(12960),
  },
  {
    id: "deploy-205",
    branch: sortMenu,
    commitMessage: "Add a status sort option to the components example",
    environment: "staging",
    status: "ready",
    deployedAt: minutesAgo(20160),
  },
  {
    id: "deploy-204",
    branch: main,
    commitMessage: "Ship the components example and its Route Handler",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(30240),
  },
  {
    id: "deploy-203",
    branch: bulkActions,
    commitMessage: "Add the issues example with row selection",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(40320),
  },
  {
    id: "deploy-202",
    branch: main,
    commitMessage: "Set up the application shell and responsive navigation",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(50400),
  },
  {
    id: "deploy-201",
    branch: main,
    commitMessage: "Initialize the project with Tailwind CSS 4 and shadcn/ui",
    environment: "production",
    status: "ready",
    deployedAt: minutesAgo(64800),
  },
];
